/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingLoginRouteImport } from './routes/_marketing/login'
import { Route as MarketingSignupRouteImport } from './routes/_marketing/signup'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLoginRoute = MarketingLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingSignupRoute = MarketingSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => MarketingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/login': typeof MarketingLoginRoute
  '/signup': typeof MarketingSignupRoute
}
export interface FileRoutesByTo {
  '/login': typeof MarketingLoginRoute
  '/signup': typeof MarketingSignupRoute
  '/': typeof MarketingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/_marketing/login': typeof MarketingLoginRoute
  '/_marketing/signup': typeof MarketingSignupRoute
  '/_marketing/': typeof MarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/signup' | '/'
  id:
    | '__root__'
    | '/_marketing'
    | '/_marketing/login'
    | '/_marketing/signup'
    | '/_marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/login': {
      id: '/_marketing/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MarketingLoginRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/signup': {
      id: '/_marketing/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof MarketingSignupRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingLoginRoute: typeof MarketingLoginRoute
  MarketingSignupRoute: typeof MarketingSignupRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingLoginRoute: MarketingLoginRoute,
  MarketingSignupRoute: MarketingSignupRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
